<a href="https://colab.research.google.com/github/HSDevCraft/PyTorch/blob/main/Tensors_%26_its_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import torch
import numpy as np
torch.__version__

'2.2.1+cu121'

In [3]:
tensor_2d = torch.randn(2,3)
tensor_2d

tensor([[-0.4092, -0.2065, -1.5787],
        [-1.8989, -2.7562, -0.0282]])

In [9]:
tensor_3d = torch.zeros(5,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### **Tensor Ops**

In [14]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
my_torch3 = my_torch3.reshape(3, -1)
# my_torch3 = my_torch3.reshape(-1, 3)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [32]:
my_torch0 = torch.arange(10)
my_torch4 = my_torch0.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
my_torch6 = my_torch5.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [38]:
my_torch5[1] = 4096
my_torch5

tensor([   0, 4096,    2,    3,    4,    5,    6,    7,    8,    9])

In [39]:
my_torch6

tensor([[   0, 4096],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [43]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [49]:
# Grab a slice
my_torch8 = my_torch7.reshape(5 , 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [59]:
print(my_torch8[0,:])
print(my_torch8[:,0])
print(my_torch8[:,1])
print(my_torch8[:,1:])

tensor([0, 1])
tensor([0, 2, 4, 6, 8])
tensor([1, 3, 5, 7, 9])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])


#### **Tensor Math Operations**

In [64]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [66]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [67]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [68]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [69]:
# SUb Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [70]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [71]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [72]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [73]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [74]:
# Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [75]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [76]:
# Exponents / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [77]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [78]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [79]:
tensor_a

tensor([1, 2, 3, 4])

In [82]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [83]:
tensor_a

tensor([11, 14, 17, 20])